version: '3.4'

services:
  ### TRANSACTIONS MICROSERVICE
  transactions:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9000:80"
    
  db:    
    ports:
      - '9001:5432'
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "9900:80"
    restart: unless-stopped
        
volumes:
  pgadmin: