version: '3.4'

services:
  ### TRANSACTIONS MICROSERVICE
  transactions:
    container_name: transactions-service
    image: ${DOCKER_REGISTRY-}budgetly-transactions
    build:
      context: ../
      dockerfile: src/Transactions/Transactions.App/Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    container_name: db
    image: postgres    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    restart: unless-stopped
        
volumes:
  db: