version: '3.4'

services:
  ### TRANSACTIONS MICROSERVICE
  transactions:
    container_name: transactions-service
    image: ${DOCKER_REGISTRY-}budgetly-transactions
    build:
      context: .
      dockerfile: .../src/Transactions/Transactions.App/Dockerfile
    depends_on:
      - transactions-db
    restart: unless-stopped
    
  transactions-db:
    container_name: transactions-db
    image: postgres    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      PGDATA: /data/postgres
    volumes:
      - transactions-db:/data/postgres
    restart: unless-stopped
        
volumes:
  transactions-db: